#:schema https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json

# Config veriosn of resticprofile
version: "1"

# Includes for other configuration files
includes:
  - "../conf/resticprofile/conf.d/*.conf"
  - "../conf/resticprofile/profiles.d/*.yaml"
  - "../conf/resticprofile/profiles.d/*.toml"
  - "../conf/resticprofile/profiles.d/*.hcl"
  - "../conf/resticprofile/profiles.d/*.json"
